### ISSUE TITLE
It runs kinda slow

### ISSUE THREAD

**Issue by T2brozz** [EmbersArc/rpi_led_panel#1]
Hey 
i tried running the rotating square example on my 64 x 64 matrix with a pi4 4gb and only got 30 fps and non plesant flickering. 
last time I used the python binding to the original lib i got around 80 fps. I tried this lib and also [this](https://crates.io/crates/rpi-led-matrix) rust binding wich isnt much faster.
Do you have any idea how to improve the performance or stop the flickering ?

**Comment by s-nie** [comment]
If both are slow, maybe you didn't build with `--release`?

**Comment by EmbersArc** [comment]
If both are slow, maybe you didn't build with `--release`?

**Comment by T2brozz** [comment]
i tried the other one with --release yours not . i will try it tomorow

**Comment by T2brozz** [comment]
thanks it works ^^ other question is there an option to change --led-rgb-sequence from rgb to brg ?

**Comment by EmbersArc** [comment]
I just added LED sequences, can you try if it works for you?

Just add this to your `Cargo.toml`:

```toml
rpi-led-panel = { git = "https://github.com/EmbersArc/rpi_led_panel" }
```

and set the desired LED sequence in the config.
