### ISSUE TITLE
 `parallel` parameter in config not functioning as expected

### ISSUE THREAD

**Issue by lonesometraveler** [EmbersArc/rpi_led_panel#2]
Hello there! Thank you so much for your work. 

I have a question regarding the `RGBMatrixConfig`. Although the `parallel` parameter exists, I noticed that setting it to any value other than `1` doesn't seem to have any effect. (I use `Regular` hardware mapping.) Is this how it is intended to work?

To get it to work as I wanted, I had to define the `PixelDesignatorMap`'s `height` as `config.rows * config.parallel` and the `Canvas`'s `rows` as `config.rows * config.parallel`. However, I would appreciate it if you could confirm whether I did this correctly.

**Comment by EmbersArc** [comment]
Closed in #3
