### ISSUE TITLE
Possibly Incorrect Bound Check in `apply_pixel_mapper` Function

### ISSUE THREAD

**Issue by lonesometraveler** [EmbersArc/rpi_led_panel#5]
I wonder if the bound check in `apply_pixel_mapper` in `rgb_matrix.rs` is correct.

```rust
fn apply_pixel_mapper(
    shared_mapper: PixelDesignatorMap,
    mut mapper: Box<dyn MultiplexMapper>,
    config: &mut RGBMatrixConfig,
    pixel_designator: PixelDesignator,
) -> PixelDesignatorMap {
    // ...
    for y in 0..new_height {
        for x in 0..new_width {
            let [orig_x, orig_y] = mapper.map_visible_to_matrix(old_width, old_height, x, y);
            if !(0..orig_x).contains(&old_width) || !(0..orig_y).contains(&old_height) {
                eprintln!("Error in pixel mapper"); // TODO
                continue;
            }
            // ...
        }
    }
    // ...
}
```

Shouldn't we check if `orig_x` and `orig_y` are within `0..old_width` and `0..old_height` like this? 

```rust
if !(0..old_width).contains(&orig_x) || !(0..old_height).contains(&orig_y) {
    eprintln!("Error in pixel mapper");
    continue;
}
```

This approach aligns with the implementation in [hzeller/rpi-rgb-led-matrix](https://github.com/hzeller/rpi-rgb-led-matrix/blob/a3eea997a9254b83ab2de97ae80d83588f696387/lib/led-matrix.cc#L580).

**Comment by EmbersArc** [comment]
You're right! Thanks a lot, should be fixed in https://github.com/EmbersArc/rpi_led_panel/commit/94409455a21a53708024fb21025da7206854fcf3.
