### ISSUE TITLE
Remapping with PixelMapper

### ISSUE THREAD

**Issue by lonesometraveler** [EmbersArc/rpi_led_panel#6]
I've noticed that the [PixelMapper](https://github.com/hzeller/rpi-rgb-led-matrix/blob/master/lib/pixel-mapper.cc) feature has not been implemented yet. (MultiplexMapper is a kind of PixelMapper, though.) 

PixelMapper provides [remapping functionalities](https://github.com/hzeller/rpi-rgb-led-matrix/tree/master/examples-api-use#remapping-coordinates) such as U Shape, Rotate, Mirror, etc.. I want to see whether you are currently working on this feature or if there are any plans for its implementation. 

I'm interested in contributing to the project and want to know if there have been any initial efforts related to PixelMapper.

**Comment by EmbersArc** [comment]
That's right, feel free to send a PR!

**Comment by lonesometraveler** [comment]
Thanks. I will send many small PRs instead of a huge PR.
